import { ETokenMode } from "./enums";

export const API_TYPE_OPTIONS = [
  { label: "Bearer Token", value: "1" },
  { label: "Api Token", value: "0" },
];

export const TOKEN_MODE_OPTIONS = [
  { label: "Development", value: ETokenMode.DEVELOPMENT },
  { label: "Production", value: ETokenMode.PRODUCTION },
];

export const FUNCTION_PERMISSION = {
  ADD_AND_REMOVE_DATABASE_CONFIG: "ADD_AND_REMOVE_DATABASE_CONFIG",
  ADD_AND_REMOVE_GROUP_SETTING: "ADD_AND_REMOVE_GROUP_SETTING",
  ADD_AND_REMOVE_MCP: "ADD_AND_REMOVE_MCP",
  ADD_AND_REMOVE_MEMBERS: "ADD_AND_REMOVE_MEMBERS",
  ADD_AND_REMOVE_PROJECT: "ADD_AND_REMOVE_PROJECT",
  ADD_AND_REMOVE_PROVIDER: "ADD_AND_REMOVE_PROVIDER",
  ADD_AND_REMOVE_SHARED_TOKEN: "ADD_AND_REMOVE_SHARED_TOKEN",
  ADD_AND_REMOVE_SKILL: "ADD_AND_REMOVE_SKILL",
  ADD_AND_REMOVE_STORAGE: "ADD_AND_REMOVE_STORAGE",
  DELETE_FILE: "DELETE_FILE",
  DOWNLOAD_FILE: "DOWNLOAD_FILE",
  READ_ONLY: "READ_ONLY",
  RENAME_GROUP_ID: "RENAME_GROUP_ID",
  UPLOAD_FILE: "UPLOAD_FILE",
} as const;

export type FunctionPermissionKey = (typeof FUNCTION_PERMISSION)[keyof typeof FUNCTION_PERMISSION];
